"""Meta-agent scaffolding — diagnose failures and propose improvements."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class MetaAgent:
    """Reads program directives and experiment history to propose changes.

    In a full deployment this would invoke an LLM to generate patches.
    The current implementation provides deterministic scaffolding that
    external callers (or a future LLM integration) can build on.
    """

    project_root: Path = field(default_factory=Path.cwd)
    program_text: str = ""

    def diagnose(self, results: list[dict]) -> str:
        """Analyse task results and return a human-readable diagnosis.

        Parameters
        ----------
        results : list[dict]
            Each dict must contain at least ``name``, ``passed``, ``score``,
            and ``output`` keys (as returned by ``TaskRunner.run_task``).
        """
        if not results:
            return "No task results to diagnose."

        total = len(results)
        passed = sum(1 for r in results if r["passed"])
        failed = total - passed
        avg_score = sum(r["score"] for r in results) / total if total else 0.0

        lines: list[str] = [
            f"Diagnosis: {passed}/{total} tasks passed (avg score {avg_score:.3f}).",
        ]

        if failed == 0:
            lines.append("All tasks passing — look for optimisation opportunities.")
            return "\n".join(lines)

        lines.append("")
        lines.append("Failed tasks:")
        for r in results:
            if not r["passed"]:
                # Truncate long output for the summary.
                snippet = (r.get("output") or "")[:300]
                lines.append(f"  - {r['name']}: {snippet}")

        # Identify common failure patterns.
        timeout_failures = [r for r in results if "timed out" in (r.get("output") or "")]
        if timeout_failures:
            names = ", ".join(r["name"] for r in timeout_failures)
            lines.append(f"\nTimeout pattern detected in: {names}")

        import_failures = [
            r for r in results if "ModuleNotFoundError" in (r.get("output") or "")
        ]
        if import_failures:
            names = ", ".join(r["name"] for r in import_failures)
            lines.append(f"\nMissing-module pattern detected in: {names}")

        return "\n".join(lines)

    def propose_changes(self, diagnosis: str) -> list[dict]:
        """Generate a list of proposed modifications based on the diagnosis.

        Each proposal is a dict with keys:
            - ``file``: path to the file to modify
            - ``description``: what the change does
            - ``diff_summary``: short textual summary of the diff

        Returns an empty list when the diagnosis indicates full convergence
        (all tasks passing with no obvious improvements).
        """
        if "All tasks passing" in diagnosis:
            return []

        # Scaffold: return a generic placeholder proposal.
        # In production this would call an LLM to generate real patches.
        proposals: list[dict] = []

        if "Timeout pattern" in diagnosis:
            proposals.append(
                {
                    "file": "task_runner.py",
                    "description": "Increase default timeout or optimise slow tasks",
                    "diff_summary": "adjust timeout / add caching",
                }
            )

        if "Missing-module pattern" in diagnosis:
            proposals.append(
                {
                    "file": "requirements.txt",
                    "description": "Add missing dependencies",
                    "diff_summary": "append missing packages to requirements.txt",
                }
            )

        if not proposals:
            proposals.append(
                {
                    "file": "solution.py",
                    "description": "Attempt a fix for failing tasks (placeholder)",
                    "diff_summary": "LLM-generated patch would go here",
                }
            )

        return proposals

    def apply_changes(self, proposals: list[dict]) -> None:
        """Apply proposed changes to the working tree.

        This is a **placeholder** — in a real deployment, the meta-agent
        would write actual file patches (e.g. generated by an LLM).

        Currently it writes a breadcrumb file so the experiment loop can
        detect that *something* changed.
        """
        breadcrumb = self.project_root / ".forge_last_proposals.txt"
        lines = [
            f"- [{p.get('file', '?')}] {p.get('description', '')}" for p in proposals
        ]
        breadcrumb.write_text("\n".join(lines) + "\n")
